create table tb_client (id bigint not null auto_increment, celular varchar(255), email varchar(255), endereco varchar(255), login varchar(255), password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table tb_client_role (client_id bigint not null, role_id bigint not null, primary key (client_id, role_id)) engine=InnoDB;
create table tb_password_recover (expiration datetime(6) not null, id bigint not null auto_increment, email varchar(255) not null, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table tb_role (id bigint not null auto_increment, authority varchar(255), primary key (id)) engine=InnoDB;
create table tb_room (valor float(53), id bigint not null auto_increment, descricao TEXT, imagem_url varchar(255), primary key (id)) engine=InnoDB;
create table tb_stay (data_entrada DATE, client_id bigint, id bigint not null auto_increment, room_id bigint, primary key (id)) engine=InnoDB;
alter table tb_client add constraint UKcj5tragl28dvlrf3nr4rum3p0 unique (endereco);
alter table tb_client add constraint UKelyk72q8sk3d936a6q7wbt04n unique (login);
alter table tb_client add constraint UK1bbd5v2sqsujx313sx6n57in4 unique (password);
alter table tb_client_role add constraint FKcy1gcv6wya3x467j93r061t9p foreign key (role_id) references tb_role (id);
alter table tb_client_role add constraint FKa4i5py4f21jvbfvxg6a1fhf62 foreign key (client_id) references tb_client (id);
alter table tb_stay add constraint FKmm1334j8hldpocubs0g9kf5xc foreign key (client_id) references tb_client (id);
alter table tb_stay add constraint FK58amo6mu2g4gm7a64521keqx foreign key (room_id) references tb_room (id);
INSERT INTO tb_client (nome, email, senha, login, celular, endereco) VALUES ('Anna Karenina', 'anna@ifmg.edu.br', '123', 'annak', '31999999999', 'Rua das Flores, 100');
INSERT INTO tb_client (nome, email, senha, login, celular, endereco) VALUES ('João Silva', 'joao@email.com', '456', 'joaos', '31988888888', 'Av. Central, 200');
INSERT INTO tb_room (descricao, valor, imagem_url) VALUES ('Quarto Simples com ventilador', 120.00, '/images/quarto_simples.jpg');
INSERT INTO tb_room (descricao, valor, imagem_url) VALUES ('Suíte Master com ar-condicionado e varanda', 300.00, '/images/suite_master.jpg');
